apiVersion: apps/v1
kind: Deployment
metadata:
  name: muskhkhxxa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: muskhkhxxa
  template:
    metadata:
      labels:
        app: muskhkhxxa
    spec:
      containers:
      - image: okteto.dev/muskhkhxxa:latest
        name: muskhkhxxa
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "8acceb60-9afb-49e9-902f-2b2322e41251"
        - name: Vless_Path
          value: "/2b2322e41251vless"
        - name: Vmess_UUID
          value: "8acceb60-9afb-49e9-902f-2b2322e41251"
        - name: Vmess_Path
          value: "/2b2322e41251vmess"
        - name: Share_Path
          value: "/v2link"
